// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: common.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgId int32

const (
	MsgId_Invalid MsgId = 0
	// client <> game
	MsgId_CToG_RoleLogin    MsgId = 1 //[(req) = "RoleLoginReq", (ack) = "RoleLoginAck", (desc) = "玩家登录"]
	MsgId_CToG_RoleRegister MsgId = 2 //[(req) = "RoleRegisterReq", (ack) = "RoleLoginAck", (desc) = "玩家注册"]
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0: "Invalid",
		1: "CToG_RoleLogin",
		2: "CToG_RoleRegister",
	}
	MsgId_value = map[string]int32{
		"Invalid":           0,
		"CToG_RoleLogin":    1,
		"CToG_RoleRegister": 2,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type ResultId int32

const (
	ResultId_ResultIdInvalid ResultId = 0
	ResultId_Success         ResultId = 1 // 成功
	ResultId_RoleNotExist    ResultId = 2 // 玩家不存在
	ResultId_System          ResultId = 3 // 系统错误
	ResultId_InvalidParams   ResultId = 4 // 参数错误
	ResultId_Fail            ResultId = 5 // 请求失败
	ResultId_ViolateWord     ResultId = 6 // 违规词语
	ResultId_SystemBusy      ResultId = 7 // 系统忙
)

// Enum value maps for ResultId.
var (
	ResultId_name = map[int32]string{
		0: "ResultIdInvalid",
		1: "Success",
		2: "RoleNotExist",
		3: "System",
		4: "InvalidParams",
		5: "Fail",
		6: "ViolateWord",
		7: "SystemBusy",
	}
	ResultId_value = map[string]int32{
		"ResultIdInvalid": 0,
		"Success":         1,
		"RoleNotExist":    2,
		"System":          3,
		"InvalidParams":   4,
		"Fail":            5,
		"ViolateWord":     6,
		"SystemBusy":      7,
	}
)

func (x ResultId) Enum() *ResultId {
	p := new(ResultId)
	*p = x
	return p
}

func (x ResultId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultId) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ResultId) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ResultId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultId.Descriptor instead.
func (ResultId) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x72, 0x70, 0x63, 0x2a, 0x3f, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x54, 0x6f,
	0x47, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x15, 0x0a,
	0x11, 0x43, 0x54, 0x6f, 0x47, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x10, 0x02, 0x2a, 0x88, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49,
	0x64, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x49, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10,
	0x03, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x05, 0x12, 0x0f,
	0x0a, 0x0b, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x10, 0x06, 0x12,
	0x0e, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x42, 0x75, 0x73, 0x79, 0x10, 0x07, 0x42,
	0x06, 0x5a, 0x04, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_goTypes = []interface{}{
	(MsgId)(0),    // 0: rpc.MsgId
	(ResultId)(0), // 1: rpc.ResultId
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
