// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	game.proto
	common.proto

It has these top-level messages:
	FailAck
	RoleLoginReq
	RoleLoginAck
	RoleRegisterReq
	ItemInfo
	ItemData
	EMail
	MailInfo
	SystemMail
	MailData
	ReceiveMailRewardReq
	ReceiveMailRewardAck
	RoleMailNtf
	HeartBeatReq
	HeatBeatAck
	CommonReq
	CommonAck
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EMail_Status int32

const (
	EMail_StatusNotRead       EMail_Status = 0
	EMail_StatusReceiveReward EMail_Status = 1
	EMail_StatusDeleted       EMail_Status = 2
)

var EMail_Status_name = map[int32]string{
	0: "StatusNotRead",
	1: "StatusReceiveReward",
	2: "StatusDeleted",
}
var EMail_Status_value = map[string]int32{
	"StatusNotRead":       0,
	"StatusReceiveReward": 1,
	"StatusDeleted":       2,
}

func (x EMail_Status) String() string {
	return proto.EnumName(EMail_Status_name, int32(x))
}
func (EMail_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type EMail_ReceiveType int32

const (
	EMail_ReceiveTypeSingle EMail_ReceiveType = 0
	EMail_ReceiveTypeAll    EMail_ReceiveType = 1
)

var EMail_ReceiveType_name = map[int32]string{
	0: "ReceiveTypeSingle",
	1: "ReceiveTypeAll",
}
var EMail_ReceiveType_value = map[string]int32{
	"ReceiveTypeSingle": 0,
	"ReceiveTypeAll":    1,
}

func (x EMail_ReceiveType) String() string {
	return proto.EnumName(EMail_ReceiveType_name, int32(x))
}
func (EMail_ReceiveType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

type FailAck struct {
	ResultId ResultId `protobuf:"varint,1,opt,name=ResultId,enum=rpc.ResultId" json:"ResultId,omitempty"`
	ErrMsg   string   `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
}

func (m *FailAck) Reset()                    { *m = FailAck{} }
func (m *FailAck) String() string            { return proto.CompactTextString(m) }
func (*FailAck) ProtoMessage()               {}
func (*FailAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FailAck) GetResultId() ResultId {
	if m != nil {
		return m.ResultId
	}
	return ResultId_ResultIdInvalid
}

func (m *FailAck) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type RoleLoginReq struct {
	RoleId  int32  `protobuf:"varint,1,opt,name=RoleId" json:"RoleId,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
}

func (m *RoleLoginReq) Reset()                    { *m = RoleLoginReq{} }
func (m *RoleLoginReq) String() string            { return proto.CompactTextString(m) }
func (*RoleLoginReq) ProtoMessage()               {}
func (*RoleLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RoleLoginReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleLoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RoleLoginAck struct {
	ResultId      ResultId    `protobuf:"varint,1,opt,name=ResultId,enum=rpc.ResultId" json:"ResultId,omitempty"`
	ErrMsg        string      `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	RoleId        int32       `protobuf:"varint,3,opt,name=RoleId" json:"RoleId,omitempty"`
	Account       string      `protobuf:"bytes,4,opt,name=Account" json:"Account,omitempty"`
	Name          string      `protobuf:"bytes,5,opt,name=Name" json:"Name,omitempty"`
	Level         int32       `protobuf:"varint,6,opt,name=Level" json:"Level,omitempty"`
	HasCreateRole bool        `protobuf:"varint,7,opt,name=HasCreateRole" json:"HasCreateRole,omitempty"`
	MailInfos     []*MailInfo `protobuf:"bytes,8,rep,name=MailInfos" json:"MailInfos,omitempty"`
}

func (m *RoleLoginAck) Reset()                    { *m = RoleLoginAck{} }
func (m *RoleLoginAck) String() string            { return proto.CompactTextString(m) }
func (*RoleLoginAck) ProtoMessage()               {}
func (*RoleLoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RoleLoginAck) GetResultId() ResultId {
	if m != nil {
		return m.ResultId
	}
	return ResultId_ResultIdInvalid
}

func (m *RoleLoginAck) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RoleLoginAck) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleLoginAck) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RoleLoginAck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleLoginAck) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RoleLoginAck) GetHasCreateRole() bool {
	if m != nil {
		return m.HasCreateRole
	}
	return false
}

func (m *RoleLoginAck) GetMailInfos() []*MailInfo {
	if m != nil {
		return m.MailInfos
	}
	return nil
}

type RoleRegisterReq struct {
	RoleId  int32  `protobuf:"varint,1,opt,name=RoleId" json:"RoleId,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Gender  int32  `protobuf:"varint,4,opt,name=Gender" json:"Gender,omitempty"`
}

func (m *RoleRegisterReq) Reset()                    { *m = RoleRegisterReq{} }
func (m *RoleRegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RoleRegisterReq) ProtoMessage()               {}
func (*RoleRegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RoleRegisterReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleRegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RoleRegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleRegisterReq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ItemInfo struct {
	ItemId      int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	Count       int32 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
	ReceiveTime int64 `protobuf:"varint,3,opt,name=ReceiveTime" json:"ReceiveTime,omitempty"`
}

func (m *ItemInfo) Reset()                    { *m = ItemInfo{} }
func (m *ItemInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()               {}
func (*ItemInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ItemInfo) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ItemInfo) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

type ItemData struct {
	ItemInfos []*ItemInfo `protobuf:"bytes,1,rep,name=ItemInfos" json:"ItemInfos,omitempty"`
}

func (m *ItemData) Reset()                    { *m = ItemData{} }
func (m *ItemData) String() string            { return proto.CompactTextString(m) }
func (*ItemData) ProtoMessage()               {}
func (*ItemData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ItemData) GetItemInfos() []*ItemInfo {
	if m != nil {
		return m.ItemInfos
	}
	return nil
}

type EMail struct {
}

func (m *EMail) Reset()                    { *m = EMail{} }
func (m *EMail) String() string            { return proto.CompactTextString(m) }
func (*EMail) ProtoMessage()               {}
func (*EMail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type MailInfo struct {
	MailId      int64        `protobuf:"varint,1,opt,name=MailId" json:"MailId,omitempty"`
	Status      EMail_Status `protobuf:"varint,2,opt,name=Status,enum=rpc.EMail_Status" json:"Status,omitempty"`
	ItemInfos   []*ItemInfo  `protobuf:"bytes,3,rep,name=ItemInfos" json:"ItemInfos,omitempty"`
	Title       string       `protobuf:"bytes,4,opt,name=Title" json:"Title,omitempty"`
	Content     string       `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	ReceiveTime int64        `protobuf:"varint,6,opt,name=ReceiveTime" json:"ReceiveTime,omitempty"`
	ExpireTime  int64        `protobuf:"varint,7,opt,name=ExpireTime" json:"ExpireTime,omitempty"`
}

func (m *MailInfo) Reset()                    { *m = MailInfo{} }
func (m *MailInfo) String() string            { return proto.CompactTextString(m) }
func (*MailInfo) ProtoMessage()               {}
func (*MailInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MailInfo) GetMailId() int64 {
	if m != nil {
		return m.MailId
	}
	return 0
}

func (m *MailInfo) GetStatus() EMail_Status {
	if m != nil {
		return m.Status
	}
	return EMail_StatusNotRead
}

func (m *MailInfo) GetItemInfos() []*ItemInfo {
	if m != nil {
		return m.ItemInfos
	}
	return nil
}

func (m *MailInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MailInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MailInfo) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func (m *MailInfo) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type SystemMail struct {
	SystemMailId int32       `protobuf:"varint,1,opt,name=SystemMailId" json:"SystemMailId,omitempty"`
	Title        string      `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
	Content      string      `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
	ItemInfos    []*ItemInfo `protobuf:"bytes,4,rep,name=ItemInfos" json:"ItemInfos,omitempty"`
	SendTime     int64       `protobuf:"varint,5,opt,name=SendTime" json:"SendTime,omitempty"`
	ExpireTime   int64       `protobuf:"varint,6,opt,name=ExpireTime" json:"ExpireTime,omitempty"`
}

func (m *SystemMail) Reset()                    { *m = SystemMail{} }
func (m *SystemMail) String() string            { return proto.CompactTextString(m) }
func (*SystemMail) ProtoMessage()               {}
func (*SystemMail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SystemMail) GetSystemMailId() int32 {
	if m != nil {
		return m.SystemMailId
	}
	return 0
}

func (m *SystemMail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SystemMail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SystemMail) GetItemInfos() []*ItemInfo {
	if m != nil {
		return m.ItemInfos
	}
	return nil
}

func (m *SystemMail) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *SystemMail) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type MailData struct {
	MailInfos    []*MailInfo `protobuf:"bytes,1,rep,name=MailInfos" json:"MailInfos,omitempty"`
	SystemMailId []int32     `protobuf:"varint,2,rep,packed,name=SystemMailId" json:"SystemMailId,omitempty"`
}

func (m *MailData) Reset()                    { *m = MailData{} }
func (m *MailData) String() string            { return proto.CompactTextString(m) }
func (*MailData) ProtoMessage()               {}
func (*MailData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MailData) GetMailInfos() []*MailInfo {
	if m != nil {
		return m.MailInfos
	}
	return nil
}

func (m *MailData) GetSystemMailId() []int32 {
	if m != nil {
		return m.SystemMailId
	}
	return nil
}

type ReceiveMailRewardReq struct {
	RoleId      int32             `protobuf:"varint,1,opt,name=RoleId" json:"RoleId,omitempty"`
	MailId      int64             `protobuf:"varint,2,opt,name=MailId" json:"MailId,omitempty"`
	ReceiveTYpe EMail_ReceiveType `protobuf:"varint,3,opt,name=ReceiveTYpe,enum=rpc.EMail_ReceiveType" json:"ReceiveTYpe,omitempty"`
}

func (m *ReceiveMailRewardReq) Reset()                    { *m = ReceiveMailRewardReq{} }
func (m *ReceiveMailRewardReq) String() string            { return proto.CompactTextString(m) }
func (*ReceiveMailRewardReq) ProtoMessage()               {}
func (*ReceiveMailRewardReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ReceiveMailRewardReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *ReceiveMailRewardReq) GetMailId() int64 {
	if m != nil {
		return m.MailId
	}
	return 0
}

func (m *ReceiveMailRewardReq) GetReceiveTYpe() EMail_ReceiveType {
	if m != nil {
		return m.ReceiveTYpe
	}
	return EMail_ReceiveTypeSingle
}

type ReceiveMailRewardAck struct {
	ResultId  ResultId    `protobuf:"varint,1,opt,name=ResultId,enum=rpc.ResultId" json:"ResultId,omitempty"`
	ErrMsg    string      `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	ItemInfos []*ItemInfo `protobuf:"bytes,3,rep,name=ItemInfos" json:"ItemInfos,omitempty"`
}

func (m *ReceiveMailRewardAck) Reset()                    { *m = ReceiveMailRewardAck{} }
func (m *ReceiveMailRewardAck) String() string            { return proto.CompactTextString(m) }
func (*ReceiveMailRewardAck) ProtoMessage()               {}
func (*ReceiveMailRewardAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReceiveMailRewardAck) GetResultId() ResultId {
	if m != nil {
		return m.ResultId
	}
	return ResultId_ResultIdInvalid
}

func (m *ReceiveMailRewardAck) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ReceiveMailRewardAck) GetItemInfos() []*ItemInfo {
	if m != nil {
		return m.ItemInfos
	}
	return nil
}

type RoleMailNtf struct {
	RoleId    int32       `protobuf:"varint,1,opt,name=RoleId" json:"RoleId,omitempty"`
	MailInfos []*MailInfo `protobuf:"bytes,2,rep,name=MailInfos" json:"MailInfos,omitempty"`
}

func (m *RoleMailNtf) Reset()                    { *m = RoleMailNtf{} }
func (m *RoleMailNtf) String() string            { return proto.CompactTextString(m) }
func (*RoleMailNtf) ProtoMessage()               {}
func (*RoleMailNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RoleMailNtf) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleMailNtf) GetMailInfos() []*MailInfo {
	if m != nil {
		return m.MailInfos
	}
	return nil
}

// 心跳包
type HeartBeatReq struct {
	RoleId int32 `protobuf:"varint,1,opt,name=RoleId" json:"RoleId,omitempty"`
}

func (m *HeartBeatReq) Reset()                    { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()               {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *HeartBeatReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type HeatBeatAck struct {
	ResultId  ResultId `protobuf:"varint,1,opt,name=ResultId,enum=rpc.ResultId" json:"ResultId,omitempty"`
	ErrMsg    string   `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	RoleId    int32    `protobuf:"varint,3,opt,name=RoleId" json:"RoleId,omitempty"`
	TimeStamp int64    `protobuf:"varint,4,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *HeatBeatAck) Reset()                    { *m = HeatBeatAck{} }
func (m *HeatBeatAck) String() string            { return proto.CompactTextString(m) }
func (*HeatBeatAck) ProtoMessage()               {}
func (*HeatBeatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *HeatBeatAck) GetResultId() ResultId {
	if m != nil {
		return m.ResultId
	}
	return ResultId_ResultIdInvalid
}

func (m *HeatBeatAck) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *HeatBeatAck) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *HeatBeatAck) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func init() {
	proto.RegisterType((*FailAck)(nil), "rpc.FailAck")
	proto.RegisterType((*RoleLoginReq)(nil), "rpc.RoleLoginReq")
	proto.RegisterType((*RoleLoginAck)(nil), "rpc.RoleLoginAck")
	proto.RegisterType((*RoleRegisterReq)(nil), "rpc.RoleRegisterReq")
	proto.RegisterType((*ItemInfo)(nil), "rpc.ItemInfo")
	proto.RegisterType((*ItemData)(nil), "rpc.ItemData")
	proto.RegisterType((*EMail)(nil), "rpc.EMail")
	proto.RegisterType((*MailInfo)(nil), "rpc.MailInfo")
	proto.RegisterType((*SystemMail)(nil), "rpc.SystemMail")
	proto.RegisterType((*MailData)(nil), "rpc.MailData")
	proto.RegisterType((*ReceiveMailRewardReq)(nil), "rpc.ReceiveMailRewardReq")
	proto.RegisterType((*ReceiveMailRewardAck)(nil), "rpc.ReceiveMailRewardAck")
	proto.RegisterType((*RoleMailNtf)(nil), "rpc.RoleMailNtf")
	proto.RegisterType((*HeartBeatReq)(nil), "rpc.HeartBeatReq")
	proto.RegisterType((*HeatBeatAck)(nil), "rpc.HeatBeatAck")
	proto.RegisterEnum("rpc.EMail_Status", EMail_Status_name, EMail_Status_value)
	proto.RegisterEnum("rpc.EMail_ReceiveType", EMail_ReceiveType_name, EMail_ReceiveType_value)
}

func init() { proto.RegisterFile("game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xed, 0xda, 0x49, 0x6f, 0xd2, 0x90, 0x0e, 0xa5, 0x58, 0x15, 0x42, 0xd1, 0x08, 0xa1,
	0x54, 0x48, 0x59, 0x94, 0x05, 0x2c, 0xe9, 0x8b, 0xb6, 0x52, 0xdb, 0xc5, 0xa4, 0x1b, 0xca, 0x6a,
	0x70, 0x6e, 0x23, 0x0b, 0xbf, 0xb0, 0xa7, 0x85, 0xee, 0xba, 0x62, 0xc1, 0x9f, 0xf1, 0x2f, 0x7c,
	0x04, 0x9a, 0x87, 0x63, 0xbb, 0xa5, 0xa9, 0x40, 0x65, 0x37, 0xe7, 0xf8, 0x66, 0xe6, 0x9c, 0x73,
	0xef, 0x64, 0x00, 0xa6, 0x3c, 0xc6, 0x51, 0x96, 0xa7, 0x22, 0x25, 0x4e, 0x9e, 0x05, 0xeb, 0xdd,
	0x20, 0x8d, 0xe3, 0x34, 0xd1, 0x14, 0x3d, 0x82, 0xd6, 0x7b, 0x1e, 0x46, 0x5b, 0xc1, 0x67, 0xb2,
	0x01, 0x6d, 0x86, 0xc5, 0x45, 0x24, 0x0e, 0x27, 0xbe, 0x35, 0xb0, 0x86, 0xbd, 0xcd, 0xe5, 0x51,
	0x9e, 0x05, 0xa3, 0x92, 0x64, 0xb3, 0xcf, 0x64, 0x0d, 0xbc, 0xbd, 0x3c, 0x3f, 0x2e, 0xa6, 0xbe,
	0x3d, 0xb0, 0x86, 0x4b, 0xcc, 0x20, 0xfa, 0x0e, 0xba, 0x2c, 0x8d, 0xf0, 0x28, 0x9d, 0x86, 0x09,
	0xc3, 0x2f, 0xb2, 0x4e, 0x62, 0xb3, 0xa1, 0xcb, 0x0c, 0x22, 0x3e, 0xb4, 0xb6, 0x82, 0x20, 0xbd,
	0x48, 0x84, 0xd9, 0xa0, 0x84, 0xf4, 0xda, 0xae, 0x6d, 0xf1, 0x30, 0xaa, 0x6a, 0x2a, 0x9c, 0xbb,
	0x54, 0x2c, 0x36, 0x54, 0x10, 0x02, 0x8b, 0x27, 0x3c, 0x46, 0xdf, 0x55, 0xb4, 0x5a, 0x93, 0x55,
	0x70, 0x8f, 0xf0, 0x12, 0x23, 0xdf, 0x53, 0x9b, 0x68, 0x40, 0x5e, 0xc0, 0xf2, 0x01, 0x2f, 0x76,
	0x72, 0xe4, 0x02, 0xe5, 0xb6, 0x7e, 0x6b, 0x60, 0x0d, 0xdb, 0xac, 0x49, 0x92, 0x57, 0xb0, 0x74,
	0xcc, 0xc3, 0xe8, 0x30, 0x39, 0x4f, 0x0b, 0xbf, 0x3d, 0x70, 0x86, 0x1d, 0xe3, 0xa2, 0x64, 0x59,
	0xf5, 0x9d, 0xa6, 0xf0, 0x48, 0xfe, 0x88, 0xe1, 0x34, 0x2c, 0x04, 0xe6, 0xff, 0x94, 0xe3, 0xcc,
	0x81, 0x53, 0x73, 0xb0, 0x06, 0xde, 0x3e, 0x26, 0x13, 0xcc, 0x95, 0x5d, 0x97, 0x19, 0x44, 0xcf,
	0xa0, 0x7d, 0x28, 0x30, 0x96, 0xa7, 0xcb, 0x1a, 0xb5, 0x9e, 0x9d, 0xa4, 0x91, 0x74, 0xbf, 0x33,
	0x3b, 0xc7, 0x65, 0x1a, 0x90, 0x01, 0x74, 0x18, 0x06, 0x18, 0x5e, 0xe2, 0x69, 0x68, 0x0e, 0x73,
	0x58, 0x9d, 0xa2, 0x6f, 0xf4, 0xde, 0xbb, 0x5c, 0x70, 0x99, 0x42, 0x79, 0x4e, 0xe1, 0x5b, 0xb5,
	0x14, 0x4a, 0x96, 0x55, 0xdf, 0xe9, 0x0f, 0x0b, 0xdc, 0x3d, 0x19, 0x0a, 0xdd, 0x07, 0x6f, 0x2c,
	0xb8, 0xb8, 0x28, 0xc8, 0x0a, 0x2c, 0xeb, 0xd5, 0x49, 0x2a, 0x18, 0xf2, 0x49, 0x7f, 0x81, 0x3c,
	0x85, 0xc7, 0x9a, 0x32, 0x87, 0x32, 0xfc, 0xca, 0xf3, 0x49, 0xdf, 0xaa, 0x6a, 0x77, 0x31, 0x42,
	0x81, 0x93, 0xbe, 0x4d, 0xdf, 0x56, 0x6a, 0xaf, 0x32, 0x24, 0x4f, 0x60, 0xa5, 0x06, 0xc7, 0x61,
	0x32, 0x8d, 0xb0, 0xbf, 0x40, 0x08, 0xf4, 0x6a, 0xf4, 0x56, 0x14, 0xf5, 0x2d, 0xfa, 0xcb, 0x82,
	0x76, 0xd9, 0x20, 0x19, 0x91, 0x5a, 0xeb, 0x88, 0x1c, 0x66, 0x10, 0xd9, 0x28, 0x75, 0xaa, 0x8c,
	0x7a, 0x9b, 0x2b, 0xca, 0x9b, 0xf2, 0x30, 0x32, 0x1a, 0x4b, 0x23, 0x8d, 0x24, 0x9c, 0xf9, 0x49,
	0xc8, 0xe8, 0x4f, 0x43, 0x11, 0xa1, 0x19, 0x52, 0x0d, 0x64, 0xeb, 0x77, 0xd2, 0x44, 0x60, 0x22,
	0xcc, 0x94, 0x96, 0xf0, 0x66, 0x53, 0xbc, 0x5b, 0x4d, 0x21, 0xcf, 0x01, 0xf6, 0xbe, 0x65, 0x61,
	0xae, 0x0b, 0x5a, 0xaa, 0xa0, 0xc6, 0xd0, 0x9f, 0x16, 0xc0, 0xf8, 0xaa, 0x10, 0x18, 0x4b, 0xf1,
	0x84, 0x42, 0xb7, 0x42, 0xb3, 0xc9, 0x68, 0x70, 0x95, 0x48, 0xfb, 0x0e, 0x91, 0x4e, 0x53, 0x64,
	0x23, 0x81, 0xc5, 0x7b, 0x12, 0x58, 0x87, 0xf6, 0x18, 0x93, 0x89, 0x52, 0xeb, 0x2a, 0xb5, 0x33,
	0x7c, 0xc3, 0x8b, 0x77, 0xcb, 0xcb, 0x47, 0xdd, 0xb9, 0x72, 0x00, 0xab, 0x6b, 0x68, 0xcd, 0xbf,
	0x86, 0xb7, 0x5c, 0xdb, 0x03, 0xe7, 0xa6, 0x6b, 0x7a, 0x6d, 0xc1, 0xaa, 0x09, 0x56, 0x32, 0x7a,
	0xf8, 0xe6, 0x5d, 0xd8, 0x6a, 0x76, 0xec, 0xc6, 0xec, 0xd4, 0x46, 0xf3, 0x43, 0xa6, 0x2f, 0x52,
	0x6f, 0x73, 0xad, 0x36, 0x40, 0xb5, 0x91, 0x64, 0xf5, 0x52, 0xfa, 0xfd, 0x4f, 0x12, 0x1e, 0xe8,
	0x8f, 0xf3, 0x6f, 0xc6, 0x94, 0x32, 0xe8, 0x48, 0x93, 0x52, 0xc4, 0x89, 0x38, 0xbf, 0x33, 0x81,
	0x46, 0x0f, 0xec, 0x7b, 0xfe, 0x0a, 0x5f, 0x42, 0xf7, 0x00, 0x79, 0x2e, 0xb6, 0x91, 0x8b, 0x39,
	0xb1, 0xca, 0x10, 0x3a, 0x07, 0xc8, 0x55, 0xdd, 0x7f, 0x7e, 0x34, 0x9e, 0xc1, 0x92, 0x9c, 0xab,
	0xb1, 0xe0, 0x71, 0xa6, 0x6e, 0xa4, 0xc3, 0x2a, 0x62, 0xdb, 0x3d, 0x93, 0x6f, 0xec, 0x27, 0x4f,
	0x3d, 0xae, 0xaf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x15, 0x67, 0x2d, 0x7d, 0x07, 0x00,
	0x00,
}
